#!/usr/bin/env python3
"""Convert Pokemon Yellow Legacy party-menu icons into the format
mods/pokered_plus expects: 16x32 RGBA, two stacked 16x16 frames, the four
DMG greys keyed by palette index.

    python3 tools/pokered_plus_convert_icons.py <path-to/Pokemon_Yellow_Legacy/gfx/icons>

Writes mods/pokered_plus/assets/icons/<species>.png and rewrites
mods/pokered_plus/data/icons_list.lua.

Source repo: https://github.com/cRz-Shadows/Pokemon_Yellow_Legacy
"""
import os
import sys

from PIL import Image

# palette index -> DMG grey, matching mods/examples/example_mini_conversion
SHADES = [(248, 248, 248), (168, 168, 168), (104, 104, 104), (8, 8, 8)]

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(REPO, "mods", "pokered_plus", "assets", "icons")
LIST_LUA = os.path.join(REPO, "mods", "pokered_plus", "data", "icons_list.lua")


def load_species_ids():
    ids = set()
    path = os.path.join(REPO, "data", "generated", "pokemon.lua")
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if line.endswith("= {") and line[:-3].strip().isupper():
            ids.add(line[:-3].strip())
    return ids


def convert(src_png):
    im = Image.open(src_png)
    if im.size != (16, 32):
        raise ValueError(f"{src_png}: expected 16x32, got {im.size}")
    if im.mode != "P":
        im = im.convert("P")
    idx = im.load()
    out = Image.new("RGBA", (16, 32))
    op = out.load()
    for y in range(32):
        for x in range(16):
            shade = SHADES[min(idx[x, y], 3)]
            op[x, y] = (*shade, 255)
    return out


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src_dir = sys.argv[1]
    species = load_species_ids()
    os.makedirs(OUT_DIR, exist_ok=True)

    written = []
    for name in sorted(os.listdir(src_dir)):
        if not name.endswith(".png"):
            continue
        sid = os.path.splitext(name)[0].upper()
        if sid not in species:
            continue  # null.png, politoed.png, ...
        convert(os.path.join(src_dir, name)).save(
            os.path.join(OUT_DIR, sid.lower() + ".png"))
        written.append(sid)

    written.sort()
    with open(LIST_LUA, "w", encoding="utf-8", newline="\n") as f:
        f.write("-- Generated by tools/pokered_plus_convert_icons.py.\n")
        f.write("-- Species with a bundled mini sprite under assets/icons/.\n")
        f.write("return {\n")
        for sid in written:
            f.write(f'  "{sid}",\n')
        f.write("}\n")

    print(f"converted {len(written)} icons -> {OUT_DIR}")
    missing = sorted(species - set(written))
    if missing:
        print(f"no source icon for: {', '.join(missing)}")


if __name__ == "__main__":
    main()
